import React, { useState } from 'react';
import axios from 'axios';
import PortalLayout from '../../layouts/PortalLayout';
import { User, Phone, Save, ShieldCheck } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';

const ProfileSettings = () => {
  const { toast } = useToast();
  const [user, setUser] = useState(JSON.parse(localStorage.getItem('farmliv_user')));
  const [phone, setPhone] = useState(user?.phone || '');
  const [loading, setLoading] = useState(false);

  const handleUpdate = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const cleanId = user.id.toString().split(':')[0];
      const res = await axios.put(`http://localhost:5000/api/staff/${cleanId}/profile`, { phone });
      
      // Update LocalStorage taaki session refreshed rahe
      const updatedUser = { ...user, phone: res.data.user.phone };
      localStorage.setItem('farmliv_user', JSON.stringify(updatedUser));
      setUser(updatedUser);

      toast({ title: "Profile Secured", description: "Mobile number updated in Farmliv Directory." });
    } catch (err) {
      toast({ variant: "destructive", title: "Update Failed" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <PortalLayout role="salesman">
      <div className="max-w-2xl mx-auto py-12 px-4 animate-in fade-in duration-700">
        <div className="bg-white rounded-[3.5rem] shadow-2xl border border-gray-50 overflow-hidden">
          <div className="bg-gray-900 p-12 text-white text-center">
            <div className="w-24 h-24 bg-[#2E7D32] rounded-3xl mx-auto flex items-center justify-center text-4xl font-black mb-6">
              {user.name?.charAt(0)}
            </div>
            <h2 className="text-3xl font-black uppercase italic tracking-tighter">{user.name}</h2>
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.3em] mt-2">{user.role}</p>
          </div>

          <form onSubmit={handleUpdate} className="p-12 space-y-8">
            <div className="space-y-2">
              <label className="text-[10px] font-black text-gray-400 uppercase ml-4 flex items-center gap-2">
                <Phone size={12} /> Mobile Number
              </label>
              <input 
                type="tel" 
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="w-full bg-gray-50 border-none px-8 py-5 rounded-2xl font-bold outline-none focus:ring-4 focus:ring-[#2E7D32]/5"
                placeholder="+91 XXXXX XXXXX"
              />
            </div>

            <div className="p-6 bg-green-50 rounded-2xl border border-green-100 flex items-start gap-4">
              <ShieldCheck className="text-[#2E7D32] mt-1" size={18} />
              <p className="text-[10px] font-bold text-green-800 leading-relaxed uppercase tracking-wider">
                This number will be visible on the invoices generated by you for Farmliv clients.
              </p>
            </div>

            <button 
              disabled={loading}
              className="w-full bg-gray-900 text-white py-6 rounded-3xl font-black text-[10px] uppercase tracking-widest hover:bg-[#2E7D32] transition-all flex items-center justify-center gap-3 shadow-xl"
            >
              {loading ? "Syncing..." : <><Save size={16} /> Save Profile Changes</>}
            </button>
          </form>
        </div>
      </div>
    </PortalLayout>
  );
};

export default ProfileSettings;